name: Deploy to EC2

on:
  workflow_dispatch:
  release:
    types: [created]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Bot Config File
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "config.json"
        json: ${{ secrets.BOT_CONFIG }}

    - name: Build Docker Image
      run: |
        docker build -t scatman-faruk .
        docker save -o scatman.tar scatman-faruk

    - name: Compress Docker Image
      run: |
        sudo apt install p7zip
        7zr a -mx=3 scatman.7z scatman.tar

    - name: Upload to EC2 Instance
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        passphrase: ${{ secrets.PASSPHRASE }}
        username: ${{ secrets.EC2_USERNAME }}
        privateKey: ${{ secrets.EC2_SFTP_KEY }}
        localPath: scatman.7z
        remotePath: /home/ubuntu/scatman.7z
        
    - name: SSH into EC2 Instance and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          7zr x scatman.7z
          sudo docker stop scatman-faruk
          sudo docker container rm -f scatman-faruk
          sudo docker image rm -f scatman-faruk
          sudo docker load -i /home/ubuntu/scatman.tar
          sudo docker run -d --name scatman-faruk scatman-faruk
          rm scatman.tar scatman.7z
