name: Dockerized Application Deployment

on:
  workflow_dispatch:
  release:
    types: [created]
  
jobs:
  build:
    name: Build and Package Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Import Bot Config File
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "config.json"
        json: ${{ vars.BOT_CONFIG }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ vars.DOCKER_IMG_NAME }} .
        docker save -o ${{ vars.DOCKER_IMG_NAME }}.tar ${{ vars.DOCKER_IMG_NAME }}

    - name: Compress Docker Image
      run: |
        sudo apt install p7zip-full
        7zr a -mx=3 ${{ vars.DOCKER_IMG_NAME }}.7z ${{ vars.DOCKER_IMG_NAME }}.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: ${{ vars.DOCKER_IMG_NAME }}.7z
  
  upload:
    name: Upload Docker Image to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Upload to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}

        source: './${{ vars.DOCKER_IMG_NAME }}.7z'
        target: ${{ vars.DOCKER_IMG_PATH }}
        strip_components: 1
  
  deploy:
    name: Deploy Docker Image to Server
    runs-on: ubuntu-latest
    needs: upload

    steps:
    - name: SSH into Remote Server and Stop Running Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker stop scatman-faruk
          sudo docker container rm -f scatman-faruk
          sudo docker image rm -f scatman-faruk


    - name: SSH into Remote Server and Deploy Docker Image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST}}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ vars.DOCKER_IMG_PATH }}
          7zr x ${{ vars.DOCKER_IMG_NAME }}.7z
          sudo docker load -i ${{ vars.DOCKER_IMG_PATH }}/${{ vars.DOCKER_IMG_NAME }}.tar
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} ${{ vars.DOCKER_IMG_NAME }}:latest
          rm -rf ${{ vars.DOCKER_IMG_PATH }}/${{ vars.DOCKER_IMG_NAME }}.tar
          rm -rf ${{ vars.DOCKER_IMG_PATH }}/${{ vars.DOCKER_IMG_NAME }}.7z